"""add minio_key column to images

Revision ID: 502e1ce10d4e
Revises: 914c152f3a6a
Create Date: 2025-12-28 15:09:48.899495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '502e1ce10d4e'
down_revision: Union[str, Sequence[str], None] = '914c152f3a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('object_store_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'object_store_key')
    # ### end Alembic commands ###
